version: '3.8'

services:
  db:
    image: postgres:12.3
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__MigrateOnStartup=true
      - ConnectionStrings__VehicleConnectionString=Server=db;Port=5432;User Id=test;Password=test123;Database=tellus_vehicles;
      - ConnectionStrings__TenantConnectionString=Server=db;Port=5432;User Id=test;Password=test123;Database=tellus_tenants;

volumes:
  pgdata:
